# ./docker-compose.dev-db.yml

version: '3'
services:
  mysql-development:
    platform: linux/x86_64 # m1맥북이면 있어야 에러가 안나는 걸로 알고 있어요!
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'development'
