name: CD

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v3

      - name: make artifacts dir
        run: mkdir ./artifacts/
      
      - name: create .env
        run: |
          touch .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          cat .env
      
      - name: zip artifacts
        run: zip -r ./artifacts/build.zip ./

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./artifacts/build.zip s3://payhere-wanted-d/deploy/build.zip
        
      - name: codedeploy
        run: aws deploy create-deployment --application-name payhere-nestjs --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name payhere-wanted-d --s3-location bucket=payhere-wanted-d,bundleType=zip,key=deploy/build.zip
